### ISSUE TITLE
Other Songs have the Achievements menu

### ISSUE THREAD

**Issue by Flezard** [8bitjake/PsychEngine-Lua-Achievements#2]
First of all, thank you for making this! It's awesome and I added an achievement for beating one of my songs, which shows in the menu!
I then wanted to play that song, but when I pressed enter to start the song, the achievements menu music was playing, and it played during the countdown. When the music of the song started, the achievements menu music stopped.
And, if we don't include the bg, all of the menu assets were here, and worked. I could switch achievements by pressing left and right, and it even made the sound effect.
![image_2022-08-02_134850455](https://user-images.githubusercontent.com/85451773/182367382-d46748ff-a2e6-4791-905d-4edb28668135.png)
Song was still playing completely fine behind that and I could still control the notes. I then tried launching another song, Bonedoggle Psych Port.
This song worked as intended, no music or menu assets of the achievements menu were here. I then realised that the Bonedoggle chart is in `mods\BONES\data\bonedoggle\bonedoggle.json`, as the Nightmare Cup song (the first song I talked about, the first screenshot) was in `mods\data\nightmare-cup\nightmare-cup-150cc.json` (custom difficulty for the song)

After that, I tried other songs in main mods folder, and in their own, and came with the same relusts ; main mods folder do that, as those in their own folder work perfectly fine
I asked myself what would happen if I played a song from the OG game, and when I played Week 5, it did the same thing as in Nightmare Cup or any other main mods folder song

This is a screenshot of a song with classic difficulties on notmal and it still does the thing
![image_2022-08-02_135349248](https://user-images.githubusercontent.com/85451773/182368237-4076e6d7-3108-4105-97ea-da6ed375a1ca.png)

**Comment by 8bitjake** [comment]
i was trying to make it so that you _didn't_ have to extract the system into its own folder by adding a new condition to an if statement in the achievement handler. that checked for if the mod that was loaded _didn't_ have a name. 

i assumed that this would only appear if you were using the base mod folder (so `PsychEngine/mods`), but it turns out it also appears on the base game.

i went ahead and fixed the bug and a [new release](https://github.com/8bitjake/PsychEngine-Lua-Achievements/releases/tag/1.0.1) is already out.

thanks for the report!
